name: FOSSA Analysis
on: push

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'uber-go'
    steps:
      - name: Checkout code
        uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4.0.0

      - name: FOSSA analysis
        uses: fossas/fossa-action@f61a4c0c263690f2ddb54b9822a719c25a7b608f # v1.0.0
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}

